"""PDF Report Generation Service for EEG Analysis Results."""

from io import BytesIO
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    Image, HRFlowable, PageBreak
)
from reportlab.graphics.shapes import Drawing, Rect, String
from reportlab.graphics.charts.barcharts import HorizontalBarChart
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas as rl_canvas
from ..core.logging_config import get_app_logger
from .narrative_service import NarrativeService
from ..config import APP_VERSION

logger = get_app_logger(__name__)

# Color palette - professional, subdued colors
COLORS = {
    'primary': colors.HexColor('#5a6c7d'),
    'secondary': colors.HexColor('#6c9bd1'),
    'text': colors.HexColor('#333333'),
    'light_gray': colors.HexColor('#f5f7fa'),
    'border': colors.HexColor('#e0e0e0'),
    'warning': colors.HexColor('#f0ad4e'),
    'success': colors.HexColor('#5cb85c'),
}

# Band power colors - muted versions
BAND_COLORS = {
    'delta': colors.HexColor('#7B1FA2'),  # Muted purple
    'theta': colors.HexColor('#1976D2'),  # Muted blue
    'alpha': colors.HexColor('#388E3C'),  # Muted green
    'beta': colors.HexColor('#F57C00'),   # Muted orange
    'gamma': colors.HexColor('#D32F2F'),  # Muted red
}


def make_footer_canvas(version: str):
    """Factory that returns a FooterCanvas subclass configured with the given version string.

    ReportLab's multiBuild performs two passes: the first collects page count,
    the second renders with that count available via self._doc.page.
    We hook into showPage() to draw the footer on every page.
    """
    class FooterCanvas(rl_canvas.Canvas):
        _version = version

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self._saved_page_states: list = []

        def showPage(self):
            self._saved_page_states.append(dict(self.__dict__))
            self._startPage()  # type: ignore[attr-defined]

        def save(self):
            total = len(self._saved_page_states)
            for state in self._saved_page_states:
                self.__dict__.update(state)
                self._draw_footer(self._pageNumber, total)  # type: ignore[attr-defined]
                rl_canvas.Canvas.showPage(self)
            rl_canvas.Canvas.save(self)

        def _draw_footer(self, page_num: int, total: int):
            self.saveState()
            self.setFont('Helvetica', 7)
            self.setFillColor(colors.gray)
            # Split disclaimer across two lines to avoid overlap
            self.drawString(
                18 * mm, 16 * mm,
                "This report is generated by an automated support tool and does not constitute a clinical diagnosis.",
            )
            self.drawString(
                18 * mm, 11 * mm,
                "All findings require interpretation by a qualified healthcare professional.",
            )
            self.setFont('Helvetica', 8)
            right_text = f"Page {page_num} of {total} | v{self._version}"
            self.drawRightString(192 * mm, 11 * mm, right_text)
            self.restoreState()

    return FooterCanvas


class PDFReportService:
    """Generate professional clinical PDF reports for EEG analysis results."""
    
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
        self._narrative_service = NarrativeService()
    
    def _setup_custom_styles(self):
        """Setup custom paragraph styles for the report."""
        # Title style - left aligned for professional look
        self.styles.add(ParagraphStyle(
            name='ReportTitle',
            parent=self.styles['Heading1'],
            fontSize=18,
            textColor=colors.black,
            spaceAfter=2,
            spaceBefore=0,
            alignment=0,  # Left align
            leftIndent=0,
        ))
        
        # Section header style - no left indent to align with text
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=12,
            textColor=colors.black,
            spaceBefore=6,
            spaceAfter=2,
            leftIndent=0,
            firstLineIndent=0,
            bulletIndent=0,
        ))
        
        # Subsection style
        self.styles.add(ParagraphStyle(
            name='Subsection',
            parent=self.styles['Heading3'],
            fontSize=11,
            textColor=colors.black,
            spaceBefore=4,
            spaceAfter=2,
            leftIndent=0,
            firstLineIndent=0,
            bulletIndent=0,
        ))
        
        # Normal text with compact spacing
        self.styles.add(ParagraphStyle(
            name='ReportBody',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.black,
            spaceBefore=2,
            spaceAfter=2,
            leading=12,
            leftIndent=0,
        ))
        
        # Disclaimer style
        self.styles.add(ParagraphStyle(
            name='Disclaimer',
            parent=self.styles['Normal'],
            fontSize=9,
            textColor=colors.black,
            spaceBefore=6,
            spaceAfter=4,
            leading=11,
            leftIndent=0,
        ))
        
        # Classification result style
        self.styles.add(ParagraphStyle(
            name='Classification',
            parent=self.styles['Normal'],
            fontSize=12,
            textColor=colors.black,
            alignment=0,  # Left align
            spaceBefore=6,
            spaceAfter=6,
            leftIndent=0,
        ))
        
        # Footer style
        self.styles.add(ParagraphStyle(
            name='Footer',
            parent=self.styles['Normal'],
            fontSize=8,
            textColor=colors.gray,
            alignment=1,  # Center
        ))
    
    def generate_report(self, result_data: dict, clinician_data: dict) -> bytes:
        """
        Generate a PDF report for the given result data.
        
        Args:
            result_data: Dictionary containing full result details from 
                        ResultsService.get_result_with_full_details()
            clinician_data: Dictionary containing current clinician info
        
        Returns:
            bytes: PDF file content
        """
        logger.info(f"Generating PDF report for result {result_data.get('result_id')}")
        
        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=20*mm,
            leftMargin=20*mm,
            topMargin=20*mm,
            bottomMargin=25*mm,
        )
        
        # Build story (list of flowable elements)
        story = []
        
        # Build each section in spec-required order
        story.extend(self._build_header_section(result_data))
        story.extend(self._build_intended_use_section())
        story.extend(self._build_disclaimer_section())
        story.extend(self._build_subject_section(result_data))
        story.extend(self._build_recording_section(result_data))
        story.extend(self._build_data_quality_flags(result_data))
        story.extend(self._build_classification_section(result_data))
        story.extend(self._build_clinical_interpretation_section(result_data))
        story.extend(self._build_narrative_section(result_data))
        story.extend(self._build_filtered_eeg_visualization(result_data))
        story.extend(self._build_band_powers_section(result_data))
        story.extend(self._build_ratios_section(result_data))
        story.extend(self._build_intervention_section(result_data))
        story.extend(self._build_limitations_section())
        story.extend(self._build_signatory_section(clinician_data))
        
        # Build PDF
        doc.multiBuild(story, canvasmaker=make_footer_canvas(APP_VERSION))
        
        pdf_content = buffer.getvalue()
        buffer.close()
        
        logger.info(f"PDF report generated successfully, size: {len(pdf_content)} bytes")
        return pdf_content
    
    def _add_footer(self, canvas, doc):
        """Legacy per-page footer callback (superseded by FooterCanvas/multiBuild)."""
        canvas.saveState()
        canvas.setFont('Helvetica', 8)
        canvas.setFillColor(colors.gray)
        page_num = canvas.getPageNumber()
        text = f"Page {page_num}"
        canvas.drawCentredString(A4[0]/2, 15*mm, text)
        canvas.restoreState()
    
    def _build_header_section(self, result_data: dict) -> list:
        """Build the report header section."""
        elements = []
        
        # Title
        elements.append(Paragraph("EEG Assessment Support Report", self.styles['ReportTitle']))
        
        # Assessment date with fallback
        analysis_date = result_data.get('inferenced_at')
        if analysis_date:
            if isinstance(analysis_date, str):
                date_str = analysis_date[:10]
            else:
                date_str = analysis_date.strftime('%Y-%m-%d')
        else:
            date_str = 'Not recorded'
        
        # Left-aligned report info as two-column table
        info_data = [
            ['Report Generated:', datetime.now().strftime('%Y-%m-%d %H:%M')],
            ['Assessment Date:', date_str],
            ['Reference:', f"R-{result_data.get('result_id', 'N/A')}"],
            ['Tool:', 'EEG Assessment Tool - ADHD Classification Application'],
            ['System Version:', APP_VERSION],
        ]
        
        info_table = Table(info_data, colWidths=[40*mm, 130*mm])
        info_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#666666')),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 2),
            ('TOPPADDING', (0, 0), (-1, -1), 2),
        ]))
        
        elements.append(info_table)
        elements.append(Spacer(1, 4))
        elements.append(HRFlowable(width="100%", thickness=1, color=COLORS['border']))
        elements.append(Spacer(1, 4))
        
        return elements
    
    def _build_intended_use_section(self) -> list:
        """Build Section 5.2: Intended Use Statement."""
        elements = []
        elements.append(Paragraph("Intended Use", self.styles['SectionHeader']))

        intended_use_text = (
            "This report is produced by a clinical decision-support tool that analyzes "
            "19-channel EEG recordings to assess whether recorded brain activity patterns are consistent "
            "with ADHD subtypes in children. The tool is intended to be used by qualified clinicians "
            "including developmental pediatricians, psychiatrists, neurologists, or trained EEG technicians "
            "as one component of a broader clinical evaluation. It is not intended to serve as the "
            "sole basis for diagnosis, treatment planning, or medication decisions. The classification "
            "output must be interpreted alongside patient history, behavioral assessment, clinical "
            "observation, and other diagnostic criteria appropriate to the clinician's professional "
            "judgment."
        )

        elements.append(Paragraph(intended_use_text, self.styles['Disclaimer']))
        elements.append(Spacer(1, 4))
        return elements

    def _build_disclaimer_section(self) -> list:
        """Build Section 5.3: Prominent Automated Tool Disclaimer."""
        elements = []

        heading_style = ParagraphStyle(
            name='_DisclaimerHeading',
            parent=self.styles['Normal'],
            fontSize=14,
            fontName='Helvetica-Bold',
            textColor=colors.black,
            spaceBefore=0,
            spaceAfter=4,
            leading=16,
        )

        heading_para = Paragraph(
            "DISCLAIMER",
            heading_style,
        )

        body_text = (
            "The classification result in this report was produced by an AI-based signal processing "
            "tool. It does not constitute a definitive clinical diagnosis of ADHD or any other "
            "condition. The findings must be reviewed and interpreted by a licensed healthcare "
            "professional in the context of a complete clinical evaluation. This tool supports "
            "clinical judgment but does not replace it."
        )
        body_para = Paragraph(body_text, self.styles['Disclaimer'])

        inner_table = Table([[heading_para], [body_para]], colWidths=[150*mm])
        inner_table.setStyle(TableStyle([
            ('LEFTPADDING', (0, 0), (-1, -1), 0),
            ('RIGHTPADDING', (0, 0), (-1, -1), 0),
            ('TOPPADDING', (0, 0), (-1, -1), 0),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]))

        outer_table = Table([[inner_table]], colWidths=[170*mm])
        outer_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#fff8e1')),
            ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#e6a817')),
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
            ('RIGHTPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))

        elements.append(outer_table)
        elements.append(Spacer(1, 4))
        return elements
    
    def _build_subject_section(self, result_data: dict) -> list:
        """Build subject information section."""
        elements = []
        elements.append(Paragraph("Subject Information", self.styles['SectionHeader']))

        age = result_data.get('age')
        age_str = f"{age} years" if age is not None else 'Not recorded'

        data = [
            ['Subject Code:', result_data.get('subject_code') or 'Not recorded'],
            ['Age:', age_str],
            ['Gender:', result_data.get('gender') or 'Not recorded'],
        ]
        
        # Consistent table width: 170mm (50mm label + 120mm value)
        table = Table(data, colWidths=[50*mm, 120*mm])
        table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('TEXTCOLOR', (0, 0), (0, -1), colors.black),
            ('TEXTCOLOR', (1, 0), (1, -1), colors.black),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
            ('TOPPADDING', (0, 0), (-1, -1), 3),
            ('LEFTPADDING', (0, 0), (-1, -1), 0),
        ]))
        
        elements.append(table)
        elements.append(Spacer(1, 4))
        
        return elements
    
    def _build_recording_section(self, result_data: dict) -> list:
        """Build Section 5.5: Recording Conditions & Technical Parameters."""
        elements = []
        elements.append(Paragraph("Recording Conditions &amp; Technical Parameters", self.styles['SectionHeader']))

        # --- Environmental Context sub-section ---
        elements.append(Paragraph("Environmental Context", self.styles['Subsection']))

        caffeinated = result_data.get('caffeinated')
        medicated = result_data.get('medicated')

        env_data = [
            ['File Name:', result_data.get('file_name') or 'Not recorded'],
            ['Sleep Hours:', (f"{result_data.get('sleep_hours')} hours"
                             if result_data.get('sleep_hours') is not None else 'Not recorded')],
            ['Food Intake:', result_data.get('food_intake') or 'Not recorded'],
            ['Caffeinated:', ('Yes' if caffeinated is True
                              else ('No' if caffeinated is False else 'Not recorded'))],
            ['Medicated:', ('Yes' if medicated is True
                            else ('No' if medicated is False else 'Not recorded'))],
        ]

        if result_data.get('medication_intake'):
            env_data.append(['Medication Details:', result_data.get('medication_intake')])

        if result_data.get('notes'):
            env_data.append(['Notes:', result_data.get('notes')])

        env_table = Table(env_data, colWidths=[50*mm, 120*mm])
        env_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
            ('TOPPADDING', (0, 0), (-1, -1), 3),
            ('LEFTPADDING', (0, 0), (-1, -1), 0),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))
        elements.append(env_table)
        elements.append(Spacer(1, 4))

        # --- Technical Parameters sub-section ---
        elements.append(Paragraph("Technical Parameters", self.styles['Subsection']))

        band_powers = result_data.get('band_powers', [])
        if band_powers:
            confirmed_channels = len(set(bp['electrode'] for bp in band_powers if bp.get('electrode')))
            channels_str = f"{confirmed_channels} of 19"
        else:
            channels_str = 'Not confirmed'

        tech_data = [
            ['Montage:', '10-20 International, 19 channels'],
            ['Confirmed Channels:', channels_str],
            ['Preprocessing Applied:', 'ICA artifact removal; 0.5\u201340 Hz bandpass filter'],
        ]

        tech_table = Table(tech_data, colWidths=[50*mm, 120*mm])
        tech_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
            ('TOPPADDING', (0, 0), (-1, -1), 3),
            ('LEFTPADDING', (0, 0), (-1, -1), 0),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))
        elements.append(tech_table)
        elements.append(Spacer(1, 4))

        return elements
    
    def _build_classification_section(self, result_data: dict) -> list:
        """Build Section 5.7: Classification Result with label map and confidence display."""
        elements = []
        elements.append(PageBreak())
        elements.append(Paragraph("Classification Result", self.styles['SectionHeader']))

        CLASS_LABELS = {
            'Inattentive (ADHD-I)':           'Consistent with ADHD - Inattentive Type',
            'Combined / C (ADHD-C)':          'Consistent with ADHD - Combined Type',
            'Hyperactive-Impulsive (ADHD-H)': 'Consistent with ADHD - Hyperactive/Impulsive Type',
            'Not ADHD':                        'Findings Not Consistent with ADHD',
        }

        predicted_class = result_data.get('predicted_class', '')
        display_label = CLASS_LABELS.get(
            predicted_class,
            'Inconclusive - Findings were insufficient to support a classification in any direction.'
        )

        confidence = result_data.get('confidence_score', 0)
        confidence_pct = confidence if confidence > 1 else confidence * 100

        # Classification label (bold, 14pt)
        label_style = ParagraphStyle(
            name='_ClassLabel',
            parent=self.styles['Normal'],
            fontSize=14,
            fontName='Helvetica-Bold',
            textColor=colors.black,
            spaceBefore=4,
            spaceAfter=4,
        )
        elements.append(Paragraph(display_label, label_style))

        # Confidence score only — no tier label, no bar
        elements.append(
            Paragraph(
                f"Confidence: {confidence_pct:.1f}%",
                self.styles['ReportBody'],
            )
        )
        elements.append(Spacer(1, 8))
        return elements

    def _build_clinical_interpretation_section(self, result_data: dict) -> list:
        """Build Section 5.8: Clinical Interpretation (three paragraphs in gray box)."""
        elements = []
        elements.append(Paragraph("Clinical Interpretation", self.styles['SectionHeader']))

        CLASS_LABELS = {
            'Inattentive (ADHD-I)':           'Consistent with ADHD - Inattentive Type',
            'Combined / C (ADHD-C)':          'Consistent with ADHD - Combined Type',
            'Hyperactive-Impulsive (ADHD-H)': 'Consistent with ADHD - Hyperactive/Impulsive Type',
            'Not ADHD':                        'Findings Not Consistent with ADHD',
        }

        predicted_class = result_data.get('predicted_class', '')
        confidence = result_data.get('confidence_score', 0)
        confidence_pct = confidence if confidence > 1 else confidence * 100

        # Paragraph 1 — classification meaning
        CLASS_MEANING = {
            'Inattentive (ADHD-I)': (
                "The EEG profile associated with the Inattentive subtype typically features elevated "
                "relative theta power and reduced beta power compared to normative references. These "
                "patterns are commonly observed at the population level in inattentive-type ADHD "
                "profiles; they represent a population-level association and are not individually "
                "diagnostic."
            ),
            'Combined / C (ADHD-C)': (
                "The EEG profile associated with the Combined subtype reflects broad spectral findings "
                "across theta and beta bands, consistent with a mixed inattentive and "
                "hyperactive/impulsive presentation. Hyperactive and impulsive behavioral correlates "
                "are not directly assessable from EEG spectral analysis alone."
            ),
            'Hyperactive-Impulsive (ADHD-H)': (
                "The EEG markers associated with the Hyperactive/Impulsive subtype are less consistently "
                "differentiated in the published literature compared to the Inattentive profile. "
                "Interpretation of this classification should account for that additional uncertainty."
            ),
            'Not ADHD': (
                "The EEG recording did not exhibit the spectral markers typically associated with ADHD "
                "profiles. The absence of these markers does not exclude ADHD by other clinical means; "
                "diagnosis requires a comprehensive evaluation beyond EEG analysis."
            ),
        }
        meaning_text = CLASS_MEANING.get(
            predicted_class,
            (
                "The automated analysis was unable to produce a confident classification in any "
                "direction. The most likely contributing factor is noted in the Data Quality Flags "
                "section, if present. A repeat EEG assessment under controlled conditions is "
                "recommended before classification-dependent decisions are made."
            ),
        )

        # Paragraph 2 — confidence context
        if confidence_pct >= 80:
            confidence_text = (
                "The model produced this result with high confidence (\u2265 80%), indicating strong "
                "agreement between the recorded signal and patterns in the training data. This result "
                "may be weighted more heavily within the broader clinical assessment, while remaining "
                "one input among several."
            )
        elif confidence_pct >= 60:
            confidence_text = (
                "The model produced this result with moderate confidence (60\u201379%). The "
                "classification direction is supported but not strongly differentiated; the clinician "
                "should apply standard clinical judgment in weighting this result."
            )
        else:
            confidence_text = (
                "The model confidence is below 60%, indicating that the signal did not strongly match "
                "any single class in the training data. This result should be treated with substantial "
                "caution and should not be a primary basis for clinical decisions."
            )

        # Paragraph 3 — static reminder
        static_text = (
            "This finding is one input into a comprehensive clinical evaluation and must be interpreted "
            "alongside behavioral history, standardized assessment instruments, clinical observation, "
            "and professional judgment."
        )

        para1 = Paragraph(meaning_text, self.styles['ReportBody'])
        para2 = Paragraph(confidence_text, self.styles['ReportBody'])
        para3 = Paragraph(static_text, self.styles['ReportBody'])

        elements.append(para1)
        elements.append(Spacer(1, 4))
        elements.append(para2)
        elements.append(Spacer(1, 4))
        elements.append(para3)
        elements.append(Spacer(1, 8))
        return elements

    def _build_narrative_section(self, result_data: dict) -> list:
        """Build the arousal and attention regulation narrative section."""
        elements = []
        elements.append(Paragraph("Arousal & Attention Profile", self.styles['SectionHeader']))

        # Derive average relative band powers from stored band_powers rows
        band_powers = result_data.get('band_powers', [])
        avg_relative: dict[str, list[float]] = {}
        for bp in band_powers:
            band = str(bp.get('frequency_band', '')).lower()
            power = bp.get('relative_power', 0)
            avg_relative.setdefault(band, []).append(float(power))

        avg_relative_power = {
            band: sum(vals) / len(vals)
            for band, vals in avg_relative.items()
        }

        # Build band_ratios dict from stored ratios rows
        ratios = result_data.get('ratios', [])
        band_ratios = {
            str(r.get('ratio_name', '')): float(r.get('ratio_value', 0))
            for r in ratios
        }

        predicted_class = result_data.get('predicted_class', 'Unknown')
        confidence = result_data.get('confidence_score', 0)
        confidence_norm = confidence / 100 if confidence > 1 else confidence

        if not avg_relative_power or not band_ratios:
            elements.append(
                Paragraph(
                    "Insufficient spectral data to generate an arousal and attention profile.",
                    self.styles['ReportBody'],
                )
            )
            elements.append(Spacer(1, 8))
            return elements

        narrative = self._narrative_service.generate_arousal_narrative(
            predicted_class=predicted_class,
            confidence_score=confidence_norm,
            avg_relative_power=avg_relative_power,
            band_ratios=band_ratios,
        )

        # Render as plain paragraph
        narrative_para = Paragraph(narrative, self.styles['ReportBody'])
        elements.append(narrative_para)
        elements.append(Spacer(1, 8))
        return elements

    def _build_band_powers_section(self, result_data: dict) -> list:
        """Build Section 5.9: Relative Band Power Analysis with print-safe shade differentiation."""
        elements = []
        elements.append(PageBreak())
        elements.append(Paragraph("Relative Band Power Analysis", self.styles['SectionHeader']))

        BAND_SHADES = {
            'delta': colors.HexColor('#111111'),
            'theta': colors.HexColor('#444444'),
            'alpha': colors.HexColor('#777777'),
            'beta':  colors.HexColor('#aaaaaa'),
            'gamma': colors.HexColor('#cccccc'),
        }

        band_powers = result_data.get('band_powers', [])
        if not band_powers:
            elements.append(Paragraph("No band power data available.", self.styles['ReportBody']))
            return elements

        # Calculate average band powers across electrodes
        avg_powers: dict[str, list[float]] = {}
        for bp in band_powers:
            band = bp.get('frequency_band', '').lower()
            power = bp.get('relative_power', 0)
            avg_powers.setdefault(band, []).append(float(power))

        for band in avg_powers:
            avg_powers[band] = sum(avg_powers[band]) / len(avg_powers[band])  # type: ignore[assignment]

        band_order = ['delta', 'theta', 'alpha', 'beta', 'gamma']
        band_labels = ['Delta (0.5-4 Hz)', 'Theta (4-8 Hz)', 'Alpha (8-13 Hz)',
                       'Beta (13-30 Hz)', 'Gamma (30-100 Hz)']

        chart_data = []
        labels = []
        chart_bands = []

        for band, label in zip(band_order, band_labels):
            if band in avg_powers:
                chart_data.append(avg_powers[band] * 100)  # type: ignore[operator]
                labels.append(label)
                chart_bands.append(band)

        if chart_data:
            # Chart title
            elements.append(Paragraph(
                "Averaged Relative Band Power Across All Channels",
                self.styles['Subsection'],
            ))

            chart_height = len(chart_data) * 22
            drawing = Drawing(170 * mm, chart_height + 20)

            chart = HorizontalBarChart()
            chart.x = 50 * mm  # type: ignore[assignment]
            chart.y = 10
            chart.width = 110 * mm  # type: ignore[assignment]
            chart.height = chart_height

            # Data — reversed for top-to-bottom display
            chart.data = [list(reversed(chart_data))]

            # Apply per-band shade colors (reversed order matches chart display)
            reversed_bands = list(reversed(chart_bands))
            for i, band in enumerate(reversed_bands):
                shade = BAND_SHADES.get(band, colors.HexColor('#4a4a4a'))
                chart.bars[(0, i)].fillColor = shade
                chart.bars[(0, i)].strokeColor = colors.black
                chart.bars[(0, i)].strokeWidth = 0.5

            chart.categoryAxis.categoryNames = list(reversed(labels))
            chart.categoryAxis.labels.fontName = 'Helvetica'
            chart.categoryAxis.labels.fontSize = 9
            chart.categoryAxis.labels.dx = -5
            chart.categoryAxis.labels.textAnchor = 'end'
            chart.categoryAxis.strokeWidth = 0.5
            chart.categoryAxis.strokeColor = colors.black
            chart.categoryAxis.visibleTicks = 0

            max_val = max(chart_data)
            chart.valueAxis.valueMin = 0
            chart.valueAxis.valueMax = max_val * 1.2
            chart.valueAxis.valueStep = max_val / 4
            chart.valueAxis.labels.fontName = 'Helvetica'
            chart.valueAxis.labels.fontSize = 8
            chart.valueAxis.labelTextFormat = '%.0f%%'
            chart.valueAxis.strokeWidth = 0.5
            chart.valueAxis.strokeColor = colors.black
            chart.valueAxis.visibleGrid = True
            chart.valueAxis.gridStrokeColor = colors.HexColor('#e0e0e0')
            chart.valueAxis.gridStrokeWidth = 0.5

            chart.barWidth = 16
            chart.barSpacing = 0
            chart.groupSpacing = 0

            drawing.add(chart)

            # Value labels at end of each bar
            for i, val in enumerate(reversed(chart_data)):
                bar_y = 10 + (i * (chart_height / len(chart_data))) + (chart_height / len(chart_data) / 2) - 3
                bar_x = chart.x + (val / (max_val * 1.2)) * chart.width + 4
                val_label = String(bar_x, bar_y, f'{val:.1f}%')
                val_label.fontName = 'Helvetica'
                val_label.fontSize = 8
                val_label.fillColor = colors.black
                drawing.add(val_label)

            elements.append(drawing)
            elements.append(Spacer(1, 10))

            # Summary table
            freq_ranges = {
                'delta': '0.5-4 Hz',
                'theta': '4-8 Hz',
                'alpha': '8-13 Hz',
                'beta':  '13-30 Hz',
                'gamma': '30-100 Hz',
            }

            summary_data = [['Band', 'Frequency Range', 'Relative Power']]
            for band in band_order:
                if band in avg_powers:
                    pct = avg_powers[band] * 100  # type: ignore[operator]
                    summary_data.append([
                        band.capitalize(),
                        freq_ranges.get(band, ''),
                        f"{pct:.2f}%",
                    ])

            summary_table = Table(summary_data, colWidths=[50*mm, 70*mm, 50*mm])
            summary_table.setStyle(TableStyle([
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f0f0f0')),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.black),
                ('ALIGN', (2, 0), (2, -1), 'RIGHT'),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                ('TOPPADDING', (0, 0), (-1, -1), 6),
                ('LEFTPADDING', (0, 0), (-1, -1), 8),
                ('RIGHTPADDING', (0, 0), (-1, -1), 8),
            ]))
            elements.append(summary_table)

        elements.append(Spacer(1, 8))
        return elements
    
    def _build_ratios_section(self, result_data: dict) -> list:
        """Build Section 5.10: Clinical Ratios with Clinical Note column and TBR annotation."""
        elements = []
        elements.append(Paragraph("Clinical Ratios", self.styles['SectionHeader']))

        RATIO_NOTES = {
            'theta_beta_ratio':  'Elevated TBR may support inattention-type profiles; not independently diagnostic.',
            'theta_alpha_ratio': 'Reflects relative dominance of theta over alpha; contextual significance varies.',
            'alpha_theta_ratio': 'Inverse of theta/alpha ratio; higher values indicate relatively greater alpha activity.',
        }

        cell_style = ParagraphStyle(
            name='_RatioCell',
            parent=self.styles['Normal'],
            fontSize=9,
            leading=11,
            textColor=colors.black,
        )
        header_style = ParagraphStyle(
            name='_RatioHeader',
            parent=self.styles['Normal'],
            fontSize=9,
            leading=11,
            fontName='Helvetica-Bold',
            textColor=colors.black,
        )

        ratios = result_data.get('ratios', [])
        if not ratios:
            elements.append(Paragraph("No ratio data available.", self.styles['ReportBody']))
            return elements

        # Three-column table: Ratio Name | Value | Clinical Note
        data = [
            [
                Paragraph('Ratio Name', header_style),
                Paragraph('Value', header_style),
                Paragraph('Clinical Note', header_style),
            ]
        ]

        for ratio in ratios:
            ratio_name = ratio.get('ratio_name', '')
            name_display = ratio_name.replace('_', ' ').title()
            value = ratio.get('ratio_value', 0)
            note = RATIO_NOTES.get(ratio_name, '')
            data.append([
                Paragraph(name_display, cell_style),
                Paragraph(f"{value:.3f}", cell_style),
                Paragraph(note, cell_style),
            ])

        table = Table(data, colWidths=[55*mm, 20*mm, 95*mm])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f0f0f0')),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.black),
            ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
            ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ]))

        elements.append(table)
        elements.append(Spacer(1, 8))

        return elements

    def _build_intervention_section(self, result_data: dict) -> list:
        """Build Section 5.11: General Clinical Considerations."""
        elements = []
        elements.append(Paragraph("General Clinical Considerations", self.styles['SectionHeader']))

        preamble = (
            "The following considerations are general observations appropriate to the assessed "
            "classification. They are not personalized treatment recommendations and do not account "
            "for the subject\u2019s individual history, comorbidities, or current care plan. All "
            "clinical decisions remain the responsibility of the treating clinician."
        )
        elements.append(Paragraph(f"<i>{preamble}</i>", self.styles['ReportBody']))
        elements.append(Spacer(1, 6))

        INTERVENTION_BULLETS: dict[str, list[str]] = {
            'Inattentive (ADHD-I)': [
                'Referral for comprehensive neuropsychological evaluation',
                'Behavioral assessment by a licensed psychologist',
                'School and learning support consultation',
                'Administration of standardized inattention rating scales (e.g., Conners, BRIEF)',
            ],
            'Combined / C (ADHD-C)': [
                'All considerations listed for the Inattentive type',
                'Additional behavioral observation targeting hyperactivity and impulsivity',
                'Parent and teacher behavioral rating scales',
            ],
            'Hyperactive-Impulsive (ADHD-H)': [
                'Behavioral observation protocol',
                'Executive function assessment',
                'Occupational therapy evaluation if fine motor concerns are present',
            ],
            'Not ADHD': [
                'Consider alternative etiologies for presenting concerns',
                'Differential evaluation for anxiety, learning disabilities, or other neurodevelopmental conditions',
            ],
        }

        predicted_class = result_data.get('predicted_class', '')
        bullets = INTERVENTION_BULLETS.get(
            predicted_class,
            [
                'Repeat EEG assessment under improved recording conditions',
                'Comprehensive clinical evaluation recommended before classification-dependent decisions are made',
            ],
        )

        for bullet_text in bullets:
            elements.append(
                Paragraph(f"<bullet>&bull;</bullet> {bullet_text}", self.styles['ReportBody'])
            )

        elements.append(Spacer(1, 8))
        return elements

    def _build_data_quality_flags(self, result_data: dict) -> list:
        """Build Section 5.6: Data Quality Flags (amber box, conditional)."""
        flags = []

        # 1. Sleep deprivation
        sleep_hours = result_data.get('sleep_hours')
        if sleep_hours is not None and float(sleep_hours) <= 5:
            flags.append(
                "Sleep deprivation reported (\u2264 5 hours). Sleep loss is associated with increased "
                "slow-wave EEG activity and may inflate theta-band power readings."
            )

        # 2. Caffeine
        if result_data.get('caffeinated') is True:
            flags.append(
                "Caffeine intake reported prior to recording. Caffeine may reduce slow-wave activity "
                "and affect spectral band measurements."
            )

        # 3. Medication
        if result_data.get('medicated') is True:
            flags.append(
                "Subject was medicated at time of recording. Certain medications (e.g., stimulants, "
                "antihistamines) are known to affect EEG spectral profiles. Review medication details "
                "in the Recording Conditions section."
            )

        # 4. Low confidence
        confidence = result_data.get('confidence_score', 0)
        confidence_pct = confidence if confidence > 1 else confidence * 100
        if confidence_pct < 60:
            flags.append(
                "Model confidence is below 60%. The classification result should be treated with "
                "substantial caution and weighted less heavily in the overall clinical assessment."
            )

        # 5. Missing demographics
        if not result_data.get('age') or not result_data.get('gender'):
            flags.append(
                "One or more subject demographic fields were not recorded. This may limit the "
                "contextual interpretability of the result."
            )

        # 6. Channel count < 19
        band_powers = result_data.get('band_powers', [])
        if band_powers:
            confirmed_channels = len(set(bp['electrode'] for bp in band_powers if bp.get('electrode')))
            if confirmed_channels < 19:
                flags.append(
                    "Fewer than 19 channels were confirmed in the recording. Signal coverage may be incomplete."
                )

        if not flags:
            return []

        elements = []
        heading_style = ParagraphStyle(
            name='_DQFlagHeading',
            parent=self.styles['Normal'],
            fontSize=11,
            fontName='Helvetica-Bold',
            textColor=colors.black,
            spaceBefore=0,
            spaceAfter=6,
        )
        heading_para = Paragraph("\u26a0 Data Quality Considerations", heading_style)

        bullet_paras = [heading_para]
        for flag_text in flags:
            bullet_paras.append(
                Paragraph(f"<bullet>&bull;</bullet> {flag_text}", self.styles['ReportBody'])
            )

        inner_table = Table([[p] for p in bullet_paras], colWidths=[150*mm])
        inner_table.setStyle(TableStyle([
            ('LEFTPADDING', (0, 0), (-1, -1), 0),
            ('RIGHTPADDING', (0, 0), (-1, -1), 0),
            ('TOPPADDING', (0, 0), (-1, -1), 0),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
        ]))

        outer_table = Table([[inner_table]], colWidths=[170*mm])
        outer_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#fff8e1')),
            ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#e6a817')),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('RIGHTPADDING', (0, 0), (-1, -1), 10),
            ('TOPPADDING', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ]))

        elements.append(outer_table)
        elements.append(Spacer(1, 8))
        return elements
    
    def _build_signatory_section(self, clinician_data: dict) -> list:
        """Build Section 5.14: Signatory Block."""
        elements = []
        elements.append(Spacer(1, 20))
        elements.append(HRFlowable(width="100%", thickness=1, color=COLORS['border']))
        elements.append(Spacer(1, 15))

        # Build clinician name
        first_name = clinician_data.get('first_name', '')
        middle_name = clinician_data.get('middle_name', '')
        last_name = clinician_data.get('last_name', '')
        occupation = clinician_data.get('occupation', '')

        full_name = ' '.join(filter(None, [first_name, middle_name, last_name]))
        if not full_name:
            full_name = 'Not recorded'

        clinician_info = full_name
        if occupation:
            clinician_info += f", {occupation}"

        # Two-column signatory table with expanded right column
        sig_data = [
            ['Prepared by:', 'Reviewed and Acknowledged by:'],
            [clinician_info, 'Name:          ___________________________'],
            [f"Date: {datetime.now().strftime('%Y-%m-%d')}", 'Designation:   ___________________________'],
            ['', 'Signature:     ___________________________'],
            ['', 'Date:          ___________________________'],
        ]

        sig_table = Table(sig_data, colWidths=[85*mm, 85*mm])
        sig_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('TEXTCOLOR', (0, 0), (-1, 0), COLORS['primary']),
            ('TEXTCOLOR', (0, 1), (-1, -1), COLORS['text']),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))

        elements.append(sig_table)

        # Acknowledgment note
        ack_note = (
            "Acknowledgment by a clinician indicates that the findings of this automated report "
            "have been reviewed in the context of a complete clinical evaluation and that any "
            "clinical decisions made are based on comprehensive professional judgment."
        )
        elements.append(Spacer(1, 10))
        elements.append(Paragraph(f"<i>{ack_note}</i>", self.styles['ReportBody']))

        return elements

    def _build_limitations_section(self) -> list:
        """Build Section 5.13: System Limitations and Scope of Use."""
        elements = []
        elements.append(PageBreak())
        elements.append(Paragraph("System Limitations and Scope of Use", self.styles['SectionHeader']))

        limitations = [
            (
                "This report does not constitute a clinical diagnosis.",
                "This application is a decision-support tool. All classification outputs must "
                "be interpreted by a qualified healthcare professional.",
            ),
            (
                "The model was trained on a specific EEG dataset.",
                "Performance may vary across different EEG hardware, electrode configurations, "
                "recording environments, and subject populations not represented in the training data.",
            ),
            (
                "Confidence scores reflect model certainty, not clinical certainty.",
                "A high confidence score indicates agreement between the input signal and patterns "
                "in the training data; it does not guarantee the clinical accuracy of the classification.",
            ),
            (
                "Environmental and physiological factors affect EEG signal quality.",
                "Sleep deprivation, caffeine, medication, and subject cooperation can alter spectral "
                "measurements independent of any ADHD-related neurophysiology.",
            ),
            (
                "The tool does not assess comorbidities.",
                "Conditions that may co-occur with ADHD, including anxiety disorders, learning "
                "disabilities, sleep disorders, and mood disorders, may produce overlapping EEG "
                "signatures. This tool does not screen for or distinguish comorbid conditions.",
            ),
            (
                "The tool does not provide medication guidance.",
                "Nothing in this report should be interpreted as guidance for, or against, "
                "pharmacological intervention of any kind.",
            ),
            (
                "EEG findings are population-level associations, not individual biomarkers.",
                "Theta/beta ratio elevation and related spectral markers are observed at the population "
                "level in ADHD research; their presence or absence in an individual is neither "
                "necessary nor sufficient for diagnosis.",
            ),
            (
                "Repeat assessments are not directly comparable.",
                "The tool does not evaluate whether a subject's EEG profile has improved "
                "or worsened over time. Longitudinal interpretation requires independent "
                "clinical judgment.",
            ),
        ]

        lim_style = ParagraphStyle(
            name='_LimitationItem',
            parent=self.styles['ReportBody'],
            spaceBefore=4,
            spaceAfter=2,
        )

        for n, (title, body) in enumerate(limitations, start=1):
            elements.append(Paragraph(f"<b>{n}. {title}</b> {body}", lim_style))

        elements.append(Spacer(1, 8))
        return elements

    def _build_filtered_eeg_visualization(self, result_data: dict) -> list:
        """Embed only the filtered EEG visualization inline after the Arousal & Attention Profile."""
        import base64

        elements = []
        eeg_viz = result_data.get('eeg_visualizations', {})
        if not eeg_viz:
            return elements

        data_uri = eeg_viz.get('filtered')
        if not data_uri:
            return elements

        try:
            if ',' in data_uri:
                img_b64 = data_uri.split(',', 1)[1]
            else:
                img_b64 = data_uri

            img_bytes = base64.b64decode(img_b64)
            img_buf = BytesIO(img_bytes)

            elements.append(Paragraph("Filtered EEG Signal (0.5-40 Hz)", self.styles['Subsection']))

            reader = ImageReader(img_buf)
            iw, ih = reader.getSize()
            max_width = 170 * mm
            max_height = 110 * mm
            scale = min(max_width / iw, max_height / ih)
            display_w = iw * scale
            display_h = ih * scale

            img_buf.seek(0)
            img_flowable = Image(img_buf, width=display_w, height=display_h)
            elements.append(img_flowable)
            elements.append(Spacer(1, 8))

        except Exception as exc:
            logger.warning(
                f"Failed to embed filtered EEG visualization in PDF: {exc}",
                exc_info=True,
            )
            elements.append(
                Paragraph(
                    "<i>Could not render filtered EEG image.</i>",
                    self.styles['ReportBody'],
                )
            )

        return elements

    def _build_eeg_visualizations_section(self, result_data: dict) -> list:
        """Kept for compatibility; no longer used in story order (replaced by _build_filtered_eeg_visualization)."""
        return []
